# Generated by Django 5.1.7 on 2025-03-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitytype',
            unique_together={('project', 'name')},
        ),
    ]
