# Generated by Django 5.1.7 on 2025-04-01 04:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_entitytype_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='color',
            field=colorfield.fields.ColorField(default='#ffeb7a', image_field=None, max_length=25, samples=None),
        ),
    ]
