# Generated by Django 5.1.7 on 2025-10-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_entitytype_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextDocument',
        ),
    ]
