# Generated by Django 5.1.7 on 2025-10-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_textdocument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitytype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='entitytype',
            name='project',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
    ]
