# Generated by Django 5.1.7 on 2025-10-11 21:05

import colorfield.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_entitytype_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#f0dc48', image_field=None, max_length=25, samples=None)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_types', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
