# Generated by Django 5.1.7 on 2025-10-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_entity_entitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytype',
            name='schema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
