# Generated by Django 5.1.7 on 2025-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='label',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
