# Generated by Django 5.1.7 on 2026-02-27 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('projects', '0002_alter_entity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('annotated_text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='projects.entity')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='library.page')),
            ],
            options={
                'ordering': ['start_offset'],
            },
        ),
    ]
